name: kurt_lourens_cv
description: Kurt Lourens CV App
version: 2.0.2+37 # dart scripts\version_num_script.dart
publish_to: none

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5

  # AssistantApps
  assistantapps_flutter_common:
    # git: https://github.com/AssistantApps/Flutter.Common.git
    path: 'C:\Development\Projects\AssistantApps\assistantapps_flutter_common'

  # Base
  get_it: 7.2.0
  http: 0.13.5

  # UI
  adaptive_theme: 3.2.0
  auto_animated: 3.1.0
  bitsdojo_window: 0.1.5
  breakpoint: 1.2.0
  flutter_svg: 2.0.4

  # Misc
  after_layout: 1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0
  pubspec_parse: 1.2.0
  flutter_launcher_icons: 0.10.0

# dependency_overrides:
#   flutter_staggered_grid_view: 0.6.2

flutter_icons: ## flutter pub run flutter_launcher_icons:main
  ios: true
  android: true
  min_sdk_android: 21
  image_path: 'assets/images/fullSizeIcon.png'
  # adaptive_icon_background: 'assets/images/fullSizeIconAdaptiveBg.png'
  # adaptive_icon_foreground: 'assets/images/fullSizeIconAdaptiveFg.png'

flutter:
  uses-material-design: true

  assets:
    - assets/json/
    - assets/images/
    - assets/images/tech/
    - assets/images/company/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand/Quicksand-Medium.ttf
        - asset: assets/fonts/Quicksand/Quicksand-Bold.ttf
        - asset: assets/fonts/Quicksand/Quicksand-Light.ttf
